image: Visual Studio 2017
configuration: Debug 

environment:
  app_version: '3.1.0'

version: '$(app_version).{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

cache:
  packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  nuget restore

publish_nuget: true

nuget:
  disable_publish_on_pr: true  

build:
  publish_nuget: true
  verbosity: minimal

test:
  assemblies:
    - OSPSuite.BDDHelper.Tests.dll

skip_branch_with_pr: true

skip_tags: true

branches:
  only:
  - master
  - develop

skip_commits:
  files:
    - '*.md'

pull_requests: 
  do_not_increment_build_number: true     

#notifications:
#  - provider: Slack
#    incoming_webhook:      
#      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=    